<?php
include('../_config.php');

header('Content-type: application/xml');

echo "<?xml version='1.0' encoding='UTF-8'?>"."\n";
echo "<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>"."\n";  ?>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/</loc>
<changefreq>daily</changefreq>
<priority>1.0000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/new-season</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/type/movies</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/popular</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/drama</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/school</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/shounen+ai</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/slice+of+life</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/adventure</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/game</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/harem</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/martial+arts</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/seinen</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/action</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/comedy</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/fantasy</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/sci+fi</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/shounen</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/mystery</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/magic</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/mecha</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/demons</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/military</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/shoujo</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/romance</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/ecchi</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/super+power</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/supernatural</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/parody</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/sports</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/music</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/horror</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/psychological</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/historical</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/dementia</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/police</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/thriller</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/shoujo+ai</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/space</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/samurai</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/kids</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/yaoi</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/josei</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/vampire</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/cars</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/yuri</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/genre/dub</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2023-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2023-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2023-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2023-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2022-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2022-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2022-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2022-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2021-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2020-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2019-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2018-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2017-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2016-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2015-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/fall-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/spring-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/summer-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/winter-2014-anime</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/terms</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/dmca</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/A</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/B</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/C</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/D</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/E</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/F</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/G</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/H</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/I</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/J</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/K</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/L</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/M</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/N</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/O</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/P</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/Q</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/R</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/S</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/T</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/U</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/V</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/W</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/X</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/Y</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/az-list/Z</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/sub-category/tv-series</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/status/ongoing</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
<url>
<loc>https://<?=$_SERVER['SERVER_NAME']?>/status/completed</loc>
<changefreq>daily</changefreq>
<priority>0.8000</priority>
</url>
</urlset>